name: Deployment
description: Do the deployment

inputs:
  variable:
    required: true
    description: "Diiba"

runs:
  using: "composite"

  steps:

    - name: Echo variable given as input
      run: echo ${{ inputs.variable }}
      shell: bash
