name: Deployment
description: Do the deployment

inputs:
  variable:
    required: true
    type: string

runs:
  using: "composite"

  steps:

    - name: Echo TEST_SECRET value
      run: echo ${{ inputs.variable }}
