on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:

  deploy-testing:
    environment: testing
    concurrency: testing
    uses: back-2-95/gha-test/.github/workflows/deployment.yml
    with:
      env: testing
      variable: ${{ vars.NORMAL_VAR }}
    secrets: inherit

  deploy-production:
    environment: production
    concurrency: production
    uses: back-2-95/gha-test/.github/workflows/deployment.yml
    with:
      env: production
      variable: ${{ vars.NORMAL_VAR }}
    secrets: inherit
