on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:

  deploy-testing:

    runs-on: ubuntu-latest
    name: Deploy to testing

    environment: testing
    concurrency: testing

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/deployment.yml
        with:
          env: testing
          variable: ${{ vars.NORMAL_VAR }}
        secrets: inherit

  deploy-production:

    runs-on: ubuntu-latest
    name: Deploy to production

    environment: production
    concurrency: production

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/deployment.yml
        with:
          env: production
          variable: ${{ vars.NORMAL_VAR }}
        secrets: inherit
